### ISSUE TITLE
$2/year VPS?

### ISSUE THREAD

**Issue by icyphox** [JoshuaRLi/jrl.ninja#1]
Hey, nice website. I was curious about the $2/year VPS. Where'd you get that? I'm paying $5/month with Digital Ocean, at the moment, so your deal sounds like a steal to me.

**Comment by JoshuaRLi** [comment]
Thanks! I got mine from [LowEndBox](https://www.lowendtalk.com/discussion/112317/gullo-s-hosting-your-new-2-year-vps-is-finally-here-new-deals). Gullo's hosting is pretty great for the price (practically free).
